### PR TITLE
Make PostgresRepository fault tolerant

### PR DESCRIPTION
**Pull request by sonallux**
### Issue description
The `PostgresRepository` utilizes the connection pool feature of the `pg` library. Connections to the postgres database are kept open for reuse for the amount of time specified by the `idleTimeoutMillis` pool configuration. If a connection is closed during this time due to a database error or a network partition an error is thrown. Currently, this error is not handled and the microservices NodeJS process will terminate because of this error.

### Solution
Add an error handler to the connection pool: `pool.on('error', (err: Error, client: Client) => {...})`

### Other refactorings
While reading the documentation and the source code of the `pg` library to fix the bug, I found a lot of improvements we can add too:

- The constructor of the `Pool` object only creates internal data structures. Therefore we do not need to create a new `Pool` object on every initialization retry. 
- The `Pool` object itself does also have a `query` method. Therefore there is no need for manually creating a `Client`, performing the query and releasing the client. The `pool.query(...)` method does that all automatically with just a single method call.
- The `init(...)` method always waits till the no-op query `SELECT 1` has succeeded. This behaviour is only needed by microservices which initialize their database tables afterwards and therefore need to wait till the database itself has initialized. But for other microservices, waiting is not necessary. Also, the waiting does not guarantee that subsequent queries will succeed too because services and the network can fail at any time! Nevertheless, every database query call must be equipped with an appropriate error handler and the initial waiting is kind of useless.

### Conclusion
Because of all those points, I decided to completely refactor the `PostgresRepository` and introduce those breaking changes:
- The constructor takes a `PoolConfig` and creates the `Pool` object and adds the error handler.
- The `init` method is renamed to `waitForConnection` and does no longer takes a `PoolConfig` as an argument and it does not create the connection pool (this is done by the constructor now). Calling this method is now optional.
- Non-breaking change: Use the `pool.query(...)` method instead of creating a `Client` object manually.

For users of the `PostgresRepository` the changes are quite simple to resolve:
- move the pool configuration argument from the `init` method to the constructor
- rename the `init` method to `waitForConnection` or completely remove the call if waiting is not needed.

### CODE REVIEW

**Comment by sonallux** [comment]
@georg-schwarz @mathiaszinnen @lunedis this PR is ready for review

**Comment by georg-schwarz** [comment]
Good job!

The question I'm asking myself is how we want do deal with connection losses in the services?
How will error handling work in the services? Should they be able to use a subscribeToError function? Or do we want to handle that synchronously when requesting queries? Should we catch that specific case and throw WebExceptions 500 "Database currently not reachable" or something similar?

**Review by georg-schwarz — APPROVED** [review]

**Comment by sonallux** [comment]
>The question I'm asking myself is how we want to deal with connection losses in the services?

Well, I think that's one of the core question my thesis tries to answer... As this really depends on a lot of things, I am going to give a comprehensive answer in the new issue jvalue/open-data-service#268

---

@georg-schwarz could you please also do a new release of the `node-dry-pg` library, so we can get the change into the microservices.

**Comment by georg-schwarz** [comment]
Since we break the API it should be a major version bump. My gut feeling tells me there might be some more changes by your insights. That given, I will release as v1.0.0-alpha1. Any objections?

**Comment by sonallux** [comment]
Yes, it is a good idea of releasing a `1.0.0-alpha.1` 👍

**Comment by georg-schwarz** [comment]
Done 👍

**Pull request merged**
